version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/src/:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/public/:/app/public
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/index.html:/app/index.html
      - ./frontend/package-lock.json:/app/package-lock.json
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=iot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    volumes:
      - postgres_data_iot:/var/lib/postgresql/data
    restart: unless-stopped # Hace que el contenedor se reinicie a menos que se detenga manualmente
    ports:
      - 5433:5432 # Puerto de postgres
  # Aqui el resto de servicios
  adminer:
      image: adminer:latest
      container_name: adminer
      restart: always
      ports:
        - 7777:8080
volumes:
  postgres_data_iot:
